-- Table structure for table `classification`
-- Table structure for table `account`
CREATE TABLE public.account (
  account_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_firstname CHARACTER VARYING NOT NULL,
  account_lastname CHARACTER VARYING NOT NULL,
  account_email CHARACTER VARYING NOT NULL,
  account_password CHARACTER VARYING NOT NULL,
  account_type CHARACTER VARYING NOT NULL DEFAULT 'Client',
  CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- Table structure for table `classification`
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE public.inventory (
  inv_id INT GENERATED BY DEFAULT AS IDENTITY,
  inv_make CHARACTER VARYING NOT NULL,
  inv_model CHARACTER VARYING NOT NULL,
  inv_year CHARACTER(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image CHARACTER VARYING NOT NULL,
  inv_thumbnail CHARACTER VARYING NOT NULL,
  inv_price NUMERIC(9, 0) NOT NULL,
  inv_miles INTEGER NOT NULL,
  inv_stock INTEGER NOT NULL,
  inv_color CHARACTER VARYING NOT NULL,
  classification_id INT NOT NULL,
  CONSTRAINT inventory_pk PRIMARY KEY (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
ALTER TABLE IF EXISTS public.inventory
  ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
  REFERENCES public.classification (classification_id) MATCH SIMPLE
  ON UPDATE CASCADE
  ON DELETE NO ACTION;

-- Data for table `classification`
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

-- Query 4 from assignment2.sql
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Query 6 from assignment2.sql
UPDATE public.inventory
SET
	inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');